name: Publish to PyPI

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish (e.g. 0.2.5)"
        required: true

jobs:
  publish-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set version
        run: |
          sed -i "s/^version = .*/version = \"${{ github.event.inputs.version }}\"/" pyproject.toml
          echo "Publishing PyPI version ${{ github.event.inputs.version }}"

      - name: Build
        run: |
          pip install hatch
          hatch build

      - name: Publish
        run: |
          pip install twine
          twine upload dist/* --non-interactive
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
